# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-12 16:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0003_mealitem_meal_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealitem',
            name='meal_status',
        ),
    ]
