# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-12 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0004_remove_mealitem_meal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='meal_status',
            field=models.CharField(choices=[('planned', 'What I Plan To Eat'), ('actual', 'What I Actually Ate')], default='planned', max_length=10, verbose_name='Meal Status'),
        ),
    ]
