# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-12 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0006_mealitem_mealitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealitem',
            name='mealitem_status',
            field=models.CharField(default='planned', max_length=10, verbose_name='Meal Item Status'),
        ),
    ]
