# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-13 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0007_auto_20170912_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealitem',
            name='mealitem_status',
            field=models.CharField(choices=[('planned', 'What I Plan To Eat'), ('actual', 'What I Actually Ate')], default='planned', max_length=10, verbose_name='Meal Item Status'),
        ),
    ]
