# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-19 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_apiusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='rest_api_create_user',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
