# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-19 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_userprofile_rest_api_create_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='rest_api_create_user',
            new_name='rest_api_user',
        ),
        migrations.AddField(
            model_name='apiusers',
            name='can_create_via_api',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
