# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-20 11:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20170919_2333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiusers',
            name='can_create_via_api',
        ),
    ]
